include/robot_interfaces/finger.hpp, srcpy/py_finger.cpp
Move `RobotServer` out of `Finger` and rename classes.
Move the `RobotServer` instance out of the `Finger` class.  Instead instantiate data, server and client objects separately in the user script.  By doing so the `Finger` class becomes obsolete and is replaced by a typedef of `RobotClient` that only specifies the template parameters.
Rename the classes to better reflect their actual responsibilities:
- Robot --> RobotDriver
- RobotServer --> RobotBackend
- RobotClient --> RobotFrontend
- finger::Finger --> finger::Frontend
Further reformat, do some small refactorings and clean up a bit.
By running the `demo_real_finger.py`.
...related pull requests on other repos are ready and approved (I will update here).
=> Restructure robot_interfaces

include/robot_interfaces/finger.hpp, srcpy/py_finger.cpp
- Add a generic, templated `NJointRobotTypes<N>` structure that contains all the relevant types for a basic BLMC robot. Use this for the Finger instead of the `finger` namespace.
- Add `calibrate` to the `RobotDriver` interface and expose it through the `RobotBackend` class (needed so that the user can call it).
By running demo_real_finger.py
...before other related PRs are ready.
=> Add generic NJointRobotTypes, expose calibrate() method

include/robot_interfaces/finger_logger.hpp, include/robot_interfaces/n_joint_robot_types.hpp, srcpy/py_finger_types.cpp, srcpy/py_one_joint_types.cpp
Extend the `Action` for the N-joint robot to include both torque and position commands.
This is needed for integrating the position controller into the interface.
Adapt FingerLogger to the change of the action format (currently only torque is logged, I did not spent more time on this as we anyway plan to make the logger more generic).
By running demo applications on the Finger robot that use the position controller.
...related PR on blmc_robots is ready (need to be merged together).
=> Extend `Action` for position controller

include/robot_interfaces/pybind_helper.hpp, srcpy/py_finger_types.cpp, srcpy/py_one_joint_types.cpp, srcpy/py_two_joint_types.cpp
Add the templated helper function `create_python_bindings` that is used
to easily create Python bindings for different NJointRobotTypes without
redundant code.
- Verified demo scripts do not have import errors.
- Run demo_fake_finger.py
- Not yet tested on the robots but will do this before merging.
=> Add helper function to create Python bindings

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_frontend.hpp
Add a method `get_status()` to `RobotFrontend` so that the user can actually access the status field.
Add Python bindings for the method and for the Status struct.
With a Python script using the fake driver.
=> Add get_status() to RobotFrontend

include/robot_interfaces/robot_logger.hpp
1. Earlier the logger was logging timestamps in the scientific notation, and now it has been set to log them with a precision of 27. I just set this randomly. 
2. Added a small note to the start() method basically highlighting that if the user specifies the same filename for logging data, then any further data whenever start() is called again will be appended to the same file. That works, else to specify another filename. 
Resolves open-dynamic-robot-initiative/blmc_robots/issues/38
=> Setting a precision value for the output data in the log file

CMakeLists.txt, include/robot_interfaces/n_joint_robot_types.hpp, include/robot_interfaces/pybind_helper.hpp, python/robot_interfaces/__init__.py, srcpy/py_generic.cpp
Apparently pybind11 has problems with creating multiple bindings of the same type.  Since `Status` is not templated anymore, it was exactly the same in all "types" modules.  This compiled without error but when importing two of the resulting modules (as happening in the `__init__.py`), it raised the following error: "ImportError: generic_type: type "Status" is already registered!".
- To fix the issue mentioned above, move the binding of `Status` to a new module `py_generic`.
- To be consistent between Python and C++ remove the typedef from `NJointRobotTypes`.
- Add bindings for the constructor of `Status` and `Observation` so they can be instantiated in Python.
- Verify `import robot_interfaces` does not raise an error.
- `rosrun blmc_robots demo_fake_finger.py`
=> Remove Status from NJointRobotTypes

CMakeLists.txt, include/robot_interfaces/n_joint_robot_functions.hpp, include/robot_interfaces/n_joint_robot_types.hpp, tests/CMakeLists.txt, tests/main.cpp, tests/test_process_action.cpp
Add a function `process_desired_action()` which contains the processing
of the action (position control and safety-checks) which was originally
implemented in the `NJointBlmcRobotDriver` class in blmc_robots.
The purpose of moving it here in a separate function is to be able to
use it in other places as well and to be more testable.
For a cleaner interface wrap the function in a templated struct
`NJointRobotFunctions` similar to the `NJointRobotTypes`.
Also add unit tests for this function (implementing those already payed off:
It revealed a bug that custom gains set by the user were simply ignored.
This is already fixed in the function provided here.
By running the new unit tests (`catkin run_tests robot_interfaces`).
=> Add function process_desired_action

demos/demo.cpp, include/robot_interfaces/monitored_robot_driver.hpp, include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/robot_driver.hpp, include/robot_interfaces/robot_frontend.hpp, include/robot_interfaces/status.hpp, srcpy/py_generic.cpp
Add mechanism to report errors from the driver/backend side to the frontend (= user).
Errors are reported through the already existing `Status` messages.  For this extend `Status` with two fields `error_status` (to check if there is an error and if yes from which component) and `error_message` (contains a human readable message in case of error).
For now, this is only used to forward board errors reported via CAN to the frontend. Error cases from the backend level (e.g. timing violation) will be added in following PRs.
The backend gets errors from the driver via a new method `RobotDriver::get_error()` which simply returns an error message.  An empty string is considered to mean "no error".  This design makes implementation pretty simple but I am not sure how nice it is, so I am happy to …
=> Add mechanism for error reporting from backend to frontend

CMakeLists.txt, include/robot_interfaces/monitored_robot_driver.hpp, include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/robot_data.hpp, include/robot_interfaces/robot_frontend.hpp, include/robot_interfaces/robot_logger.hpp, package.xml
Use the time series implementation from the new time_series package
instead of the one from real_time_tools.
Note that this should not change behaviour, it simply uses the implementation from the new package instead of the old one.
By running demo_fake_finger.py from blmc_robots.
...treep config is updated: https://github.com/machines-in-motion/treep_machines_in_motion/pull/4 and corresponding merge request in git-amd.
=> Use time series from package "time_series"

include/robot_interfaces/monitored_robot_driver.hpp, include/robot_interfaces/robot_backend.hpp
- Report errors from the timing watchdog in `MonitoredRobotDriver` through the `get_error()` method of the driver.
- Implement a `CheckpointTimer` to simplify the timing code in the backend loop.
The `CheckpointTimer` class should not be implemented where it is now.  If you approve the idea in general, I would move it to real_time_tools.
=> Report timing errors to frontend

include/robot_interfaces/n_joint_robot_functions.hpp
@shrutij01 pointed out a mistake in the PD controller: The P and D parts where added but when using the velocity in the D part, it should actually be subtracted. I.e. it should be `kp * p_err - kd * vel`.
With the Finger robot, increasing the D gain.  With the old code, the robot started to move around.  With the fix it vibrates but stays at the desired position (which is the expected behaviour).
=> Fix PD controller

tests/test_process_action.cpp
In 76c5373 a bug in the position PD controller was fixed (replacing `+`
with `-`).  Since this was a conceptual mistake rather than a typo, the
corresponding unit test was also checking for the wrong result.  This
commit fixes this.
By running the unit tests.
=> Fix Unit Test for Position Controller

CMakeLists.txt, demos/demo.cpp, demos/demo_multiprocess_backend.cpp, demos/demo_multiprocess_frontend.cpp, demos/types.hpp, include/robot_interfaces/cereal_eigen.hpp, include/robot_interfaces/n_joint_robot_types.hpp, include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/robot_data.hpp, include/robot_interfaces/robot_frontend.hpp, include/robot_interfaces/robot_logger.hpp, include/robot_interfaces/status.hpp, src/CMakeLists.txt
- Split RobotData into a single-process and multi-process version.
- Add a C++ demo for multiprocessing.
The `RobotData` class remains as base class, holding the pointers to the
time series, but does not initialize them.  Initialization is done in
the derived classes `SingleProcessRobotData` (using the single process
time series) and `MultiProcessRobotData` (using the multi process time
series).
This split is needed because the originally intended design with a
if-check does not compile with template types that are not serializable,
even when only single process is used.
While doing this, also remove the `Status` argument from the templates
(the type for this is fixed anyway).
Add a multiprocess demo. It is based on demo.cpp but split into separate executables for
backend and frontend, …
=> Enable usage of multi-process time series in RobotData

include/robot_interfaces/sensors/sensor_backend.hpp
Earlier, the sensor backend was creating a realtime thread for the loop getting observations through the sensor driver and appending these to the sensor data. But as this anyway does not run in realtime, a non-realtime thread is used now. 
This fixes #40.
Through the demo_camera
=> Changing to a non-realtime thread in the sensor backend

include/robot_interfaces/sensors/pylon_driver.hpp
Sorry for the inconvenience, had missed this one line that was printing the number of devices found. Removed that.
Everything still works through the demo_camera.
- [ x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ x] All new functions/classes are documented and existing documentation is updated according to changes.
- [ x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).
=> Removed a print statement from the PylonDriver

include/robot_interfaces/n_joint_robot_types.hpp, include/robot_interfaces/robot_logger.hpp
- Change the order of time index and time stamp in the logfile.  Now
time index is the first column.
- Use more explicit prefixes for the column names (e.g. "applied_action"
instead of "(AA)").
- Change column names to lower case everywhere.
- Remove the space between the `#` and the first column name.  This way,
the first line can be interpreted as header (with first column
"#time_index"), while it can also still be interpreted as comment by
tools that don't support the header.
With `robot_fingers/demo_data_logging.py`.
=> Use more explicit column names in log file

CMakeLists.txt, include/robot_interfaces/global_signal_handler.hpp, include/robot_interfaces/monitored_robot_driver.hpp, include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_backend.hpp, src/global_signal_handler.cpp
By releasing the GIL while calling the (C++) frontend methods, other
threads can acquire it if needed.
This is, for example, needed for the pyBullet Driver where the backend
loop needs to call Python functions and needs the GIL for that.
By running the pipeline with the pyBullet driver (to be provided in another PR).
Not tested with real robot due to current lack of access.
=> Release GIL when calling C++ methods, terminate backend cleanly & add real-time mode

include/robot_interfaces/monitored_robot_driver.hpp, include/robot_interfaces/robot_backend.hpp
This is already called in `create_realtime_thread`, so there is no need
to call it again in the thread function itself.
By running it on a real-time machine without write permission to /dev/cpu_dma_latency and checking how many warnings are printed (previously two, now only one).
=> Do not set_cpu_dma_latency twice

include/robot_interfaces/robot_backend.hpp
Add a timeout to `RobotBackend` to shut down when too much time passes between creation of the backend and reception of the first action.
By default it is set to infinity, which disables it.
Also add a shutdown method to the backend which makes handling of the shutdown a bit easier.
By modifying a demo and adding sleeps.
=> RobotBackend: Add "First Action"-Timeout

include/robot_interfaces/robot_backend.hpp
It is important to release the GIL when destructing the backend, as
otherwise the program will get stuck in a dead lock in case the driver
needs to run some Python code (as is the case with the pyBullet driver).
Unfortunately, there does not seem to be a non-intrusive way to do this
in the destructor when using pybind11.
By running a script that was blocking before due to this issue (happens, when a backend instance is destroyed before the script ends (e.g. because it was created inside a function and and its scope ends).
[//]: # "Link other open pull request here that need to be merged first." …
=> Release the GIL in the constructor

demos/demo.cpp, include/robot_interfaces/example.hpp, include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/status.hpp, tests/CMakeLists.txt, tests/test_robot_backend.cpp
- Move the dummy driver from demo.cpp to a separate file example.hpp so
it can also be used in unit tests.
- Add `set_error()` and `has_error()` to `Status`.  Only keep the first
error that occurs, i.e. if `set_error()` is called on a status object
that already has an error, the error of the second call is discarded.
- Add a unit test file for `RobotBackend`.  So far, add only one test
for the `max_number_of_actions` feature.
@vincentberenz I moved the driver from your demo to a separate file as I think it is quite useful for unit tests.  However, this makes the demo.cpp less self-contained, so I'm a bit unsure if it would be better to have it in both places (i.e. add the new example.hpp which can be used for tests but also keep a copy in demo.cpp).  What do you think?
catkin run_tests …
=> Add unit test for max_number_of_actions

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_frontend.hpp
- Make methods in `RobotFrontend` const where possible.
- Rename `get_time_stamp_ms` to `get_timestamp_ms` for consistency.  Keep old name for compatibility but mark it deprecated.
By calling both `get_time_stamp_ms()` and `get_timestamp_ms()` in a test script.
=> Clean up RobotFrontend a bit

include/robot_interfaces/sensors/sensor_frontend.hpp
- Make methods of SensorFrontend const (needed so they can be called in other const functions).
- Don't use references for time index.  It is just an integer, so there is no benefit from using a const reference.
Compiled.
=> Make methods of SensorFrontend const

include/robot_interfaces/n_finger_observation.hpp, include/robot_interfaces/robot_logger.hpp
1. Add the message type prefix (e.g. "observation_") also for scalar
values.
2. Write the tip force to the correct part of the data array (previously
was overwriting joint positions).
By running the logger in with simulation backend and examining the resulting file.
=> Fix logging of tip forces

include/robot_interfaces/pybind_helper.hpp
Be consistent with naming, i.e. do not use "time_index" in the Python
bindings when it is "timeindex" in C++.
Keep the old name for now but raise a warning when it is used (using 
the same pattern already used in `get_time_stamp_ms`).
By running a script that calls both variants.
=> RobotFrontend: Use same method names in C++ and Python

include/robot_interfaces/robot_logger.hpp
Use a standard thread for the logger instead of a real-time one.
The logger is not real-time critical and by using a standard thread, it
is less likely to mess with the really time-critical robot threads.
On TriFingerPro
=> Use std::thread for logger

CMakeLists.txt, include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_logger.hpp, license.txt, package.xml
- Some refactoring to simplify the code a bit and to make the following changes easier.
- Implement method `write_current_buffer()` which writes content from the current time series buffer to a log file without running a thread in the background.  Use this to log data if the time span is short enough to be fully contained in the time series buffer.
- If the specified log file already exists, do not append to it anymore but overwrite the existing file.  The appending resulted in invalid files as the header was also written again and I anyway don't see a use-case where one would want to log independent sequences to the same file.
- Some bugfixes:
- enable restarting after stopping
- detect if stop is called without starting it first and don't attempt to write to the file in this case.
With …
=> Refactor Logger and add method to log without background thread

include/robot_interfaces/robot_backend.hpp
This reverts commit cb0832c10c2d0d6c9cd61f89b096d6a142a9b5d5.
I just learned that `PyGILState_Check()` was only added in Python 3.4 so on a normal build (based on Python 2), this will not be available.  I did not notice this because locally I build with Python 3 but after the change bamboo is failing...
=> Revert "Also check if GIL is actually held before releasing it"

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_backend.hpp
Add method to RobotBackend to wait for the first desired action to be
received.
Used in trifinger backend to start camera log only when user starts sending actions.
=> Add RobotBackend::wait_until_first_action()

include/robot_interfaces/robot_data.hpp, include/robot_interfaces/sensors/sensor_data.hpp
Use the `create_leader_ptr` and `create_follower_ptr` factories of
`MultiprocessTimeSeries` when creating them.  In case of follower, the
passed `history_size` is ignored as the actual size of the time series
will be read from the shared memory.
This is just a quick intermediate solution.  The proper one would be to add separate factory methods here as well to avoid confusion with `history_size` being ignored in case of follower.  However, this will require bigger changes on the code which I prefer to do at a later time.
Running with backend and frontend in separate processes on TriFingerPro.
[//]: …
=> Use factories of MultiprocessTimeSeries

CMakeLists.txt, include/robot_interfaces/sensors/pybind_sensors.hpp, include/robot_interfaces/sensors/sensor_log_reader.hpp, include/robot_interfaces/sensors/sensor_logger.hpp
Add the timestamps of the "observation" time series to the sensor log.  This is needed to be able to make the same "robot time index to camera time index"-matching as during runtime.
Note: This will make older senor log files unreadable.  To better handle this in the future, add a "format_version" at the beginning of the log file.  In case of future changes of the file format, the reader can first check the version and chose the correct deserialization method for the rest of the file.
Bump C++ version to 17 for the structured binding feature (`auto [foo, bar] = tuple`).
Recorded data with the new …
=> Log time series timestamps in sensor log

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_log_entry.hpp, include/robot_interfaces/robot_log_reader.hpp, include/robot_interfaces/robot_logger.hpp, include/robot_interfaces/types.hpp
Add option to store the robot log in binary format using serialization by cereal.
This results in significantly smaller log files (~100 MB instead of ~240 MB for 2 minutes on TriFingerPro) and is easier to load in C++ applications.
This is is added in addition to the CSV-log (so all existing functionality is preserved) and only available in the "write current buffer" variant.
By producing both csv and binary log on a test run on a TriFingerPro platform, converting the binary to csv and verifying that it results in the exact same values as when directly logging to CSV.  The script for converting will be added in a coming PR to robot_fingers.
=> Store robot log in binary format

include/robot_interfaces/sensors/sensor_logger.hpp
Start sensor log at oldest time index, not newest. This should ensure that the sensor observation which was active at robot
time step 0 is included in the log when starting the log after the first robot action is received.
Running it on the submission system for a while.  Out of 321 tested log files, all of them had a camera observation already for the first robot step.
In a previous test without this change, out of 263 log files, 14 did not have a camera observation for the first few robot steps (varying between 1-10).
Note that with current settings, this change increases the camera log on …
=> Start sensor log at oldest time index, not newest

include/robot_interfaces/sensors/pybind_sensors.hpp, include/robot_interfaces/sensors/sensor_backend.hpp, include/robot_interfaces/sensors/sensor_logger.hpp
- Release GIL in all Python-bound methods of the sensor interface classes.
- Add a `shutdown()` method to `SensorBackend` so it can be shut down in a way that releases the GIL.
In the simulation setup of the submission system.
=> Add public "shutdown" method to SensorBackend and relese GIL

include/robot_interfaces/n_joint_action.hpp, include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/sensors/pybind_sensors.hpp, srcpy/py_generic.cpp
Add docstrings to Python bindings.
Building the Sphinx documentation.
=> Add docstrings for some Python bindings

include/robot_interfaces/robot_logger.hpp
Detect if the robot data is empty (i.e. robot did not start) in the
`write_current_buffer*` methods as otherwise it will hang there forever.
With submission system setup on TriFingerPro (only explicitly tested `write_current_buffer_binary`).
=> RobotLogger: Detect if robot data is empty.

include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/robot_frontend.hpp, include/robot_interfaces/status.hpp, srcpy/py_generic.cpp, tests/test_robot_backend.cpp
For use in a multi-process time series, the `Status` objects need to
have fixed size.  Thus replace the variable-size `std::string` with a
fixed size `char` array.  The length is set to 64 characters which is
more than enough for our current error messages (typically < 40 chars).
Since working with plain char-arrays is pretty annoying, make it private
and only access it through methods that convert the message from/to
`std::string`.
Tested on the robot in a setup similar to the submission system.
The problem could be seen in situations where there is an error reported by the backend.  Without this …
=> Make Status::error_message fixed-size

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_backend.hpp
- Add methods `is_running()` and `get_termination_reason()` as a non-blocking alternative to `wait_until_terminated()`.
- ￼RobotBackend: Add Python bindings for `request_shutdown()`
With these methods a script running the backend can monitor the backend in a loop and shut it down upon external request.
By using the methods in a prototype for a new TriFinger submission runner.
=> RobotBackend: Add monitoring methods and pybind request_shutdown()

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_frontend.hpp
Remove some methods from `RobotFrontend` which are deprecated since a while.
For all of them there is an equivalent alternative with only the underscore removed in `time_stamp`/`time_index`, so in case they were still be used somewhere, fixing the code that used it is trivial.
Compiled the workspace and searched the whole workspace to make sure the removed methods are not mentioned anywhere.
=> RobotFrontend: Remove deprecated methods

include/robot_interfaces/robot_log_reader.hpp, include/robot_interfaces/sensors/sensor_log_reader.hpp
In both RobotLogReader and SensorLogReader check if the log file is
opened successfully before trying to deserialise it.  This is necessary
to provide a more useful error message in case of failure.
By passing paths to files that either exist or not and verifying the result.
=> Check if log file is opened successfully

CMakeLists.txt, cmake/find_boost_components.cmake, include/robot_interfaces/example.hpp, include/robot_interfaces/robot_log_reader.hpp, include/robot_interfaces/robot_logger.hpp, include/robot_interfaces/sensors/sensor_log_reader.hpp, include/robot_interfaces/sensors/sensor_logger.hpp, tests/CMakeLists.txt, tests/test_robot_logger.cpp
Use gzip compression for both the binary robot logs and the sensor logs.
Add a very simply test for the robot logger.
- By running the unit tests
- By manually gzipping an old camera log file and opening it with the new version of the SensorLogReader.
- Recorded logs on the robot and verified that they can be opened.
=> Use GZip Compression for Data Logs

CMakeLists.txt, cmake/find_boost_components.cmake, include/robot_interfaces/robot_log_reader.hpp, include/robot_interfaces/robot_logger.hpp, include/robot_interfaces/sensors/sensor_log_reader.hpp, include/robot_interfaces/sensors/sensor_logger.hpp
- Move the code for wrapping streams with gzip (de-)compression to a separate library to avoid code duplication.
- For the istream identify if the input is actually gzip compressed by checking the first two bytes for the magic number.  This allows reading both compressed and uncompressed logs and thus provides backward compatibility.
By reading both compressed and uncompressed logfiles and by running the unit tests.
=> Refactor Gzip Stream Wrappers

CMakeLists.txt, include/robot_interfaces/robot_log_entry.hpp, include/robot_interfaces/robot_log_reader.hpp, src/convert_old_robot_log.cpp
Add application to convert old robot log files (from before the change of `Status` in 4ca02a17) to the new format, so they can be read by the current version of the software.
For this make the `Status` type of `BinaryRobotLogReader` configurable and add a method `write_file()` to easily store the converted log.
By running it on some old logs.
=> Add `convert_old_robot_log`

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_logger.hpp, include/robot_interfaces/sensors/sensor_logger.hpp, tests/test_robot_logger.cpp
Refactor the `RobotLogger` and add a logging mode that uses an internal buffer (same as in SensorLogger).  This should resolve some issues we had in the past where some time steps were missing in the log because they where not in the robot data time series anymore.
This new logging method supports writing to either binary, CSV or gzipped CSV files.
The old `start()`/`stop()` methods (used for continuous writing to file) have been renamed to `start|stop_continuous_writing()`.  Further this methods are marked deprecated as I plan to remove them soon, to not make the logger too bloated (this logging …
=> Use internal buffer in RobotLogger

CMakeLists.txt, scripts/plot_trifinger_log.py
Add a simple script that can print selected fields of a given binary
robot log file.
This is supposed to serve as a replacement for robot_fingers/plot_logged_data.py which requires a CSV log file.
By running it.
=> Add script to binary trifinger robot log

include/robot_interfaces/robot_logger.hpp, tests/test_robot_logger.cpp
Do not wait for `oldest_timeindex()` when starting the logger.  Instead, simply assume that the first step is `t = 0` if there is no data yet.
This resolves an issue that `stop()` was blocking forever when the logger was stopped before any data was received.
Add unit tests to cover this case.
By running the unit tests and by using it on the submission system with a user code that does not send any actions (and thus never starts the robot).
=> fix: Do not block in RobotLogger::stop() if buffer is empty

include/robot_interfaces/sensors/sensor_logger.hpp
Instead of blocking and waiting for the oldest time index, simply start
with `t = 0` if there is no data yet in the beginning.  The same fix has
already been applied recently on the RobotLogger class and prevents the
`stop()` method from blocking forever in case the logger is stopped
before any data is received.
By running robot_fingers/trifinger_data_backend.py (without any other scripts, so no data is added to the time series) and stopping it.  Without this fix it was blocking in the "save camera log" step, with the fix it doesn't.
=> fix: Do not block sensor logger if there is no data

include/robot_interfaces/robot_backend.hpp, srcpy/py_generic.cpp
Move the (template-independent) `TerminationReason` enum out of the
`RobotBackend` class, so it can be used without having to specify
template types of the backend.  This allows to add generic Python
bindings for the enum.
Use the new Python bindings in https://github.com/open-dynamic-robot-initiative/robot_fingers/pull/122
=> Move and pybind RobotBackend TerminationReason

include/robot_interfaces/pybind_helper.hpp, package.xml, srcpy/py_generic.cpp, tests/CMakeLists.txt, tests/test_pybind_pickle.py
Add pickle-support for bound robot Action, Observation and Status types.
This implicitly also adds support for deepcopy.
Using the unit test added in this PR.
=> Pickle-support for bound Action/Observation/Status types

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_logger.hpp, tests/test_robot_logger.cpp
- Suppress deprecation warnings of own methods in Python bindings and unit tests.
- Add deprecation warnings to the corresponding Python bindings (i.e. when called from Python).
- Fix name of class in output.
By compiling and running the logger demo from robot_fingers (with local modifications).
=> Suppress internal deprecation warnings & add warnings for Python bindings

CHANGELOG.md, include/robot_interfaces/robot_backend.hpp, include/robot_interfaces/robot_data.hpp, include/robot_interfaces/robot_frontend.hpp, include/robot_interfaces/sensors/sensor_backend.hpp, include/robot_interfaces/sensors/sensor_data.hpp, include/robot_interfaces/sensors/sensor_frontend.hpp
Add Ptr/ConstPtr typedefs to relevant classes
By using them in a new (not yet public) package.
=> Add Ptr/ConstPtr typedefs to relevant classes

CHANGELOG.md, include/robot_interfaces/pybind_finger.hpp, include/robot_interfaces/pybind_helper.hpp, srcpy/py_finger_types.cpp, srcpy/py_one_joint_types.cpp, srcpy/py_solo_eight_types.cpp, srcpy/py_trifinger_types.cpp, srcpy/py_two_joint_types.cpp
The bindings of RobotData, RobotBackend, etc. can be done in a completely generic way, given that action and observation types are provided via template parameters.
The "N-joint" action and observation provided in this package are specific to the BLMC CAN robots, though, and do not necessarily fit for other robots.
Therefore separate the binding code for the two into different helper functions such that the generic part can be used with other action/observation types as well.
BREAKING CHANGE: The `create_python_bindings()` function (which includes the N-joint action/observation) is moved to `pybind_finger.hpp` and renamed to `create_blmc_can_robot_python_bindings()`.
By running something on a robot, using the Python bindings.
[//]: # "Please make sure you followed these steps before …
=> Split pybind helper into generic and robot-specific part

include/robot_interfaces/monitored_robot_driver.hpp
Without this, the monitored driver was always using the implementation of the base `RobotDriver` class, ignoring any custom implementations.
In conjunction with https://github.com/open-dynamic-robot-initiative/robot_fingers/pull/150.
=> fix (monitored driver): Forward call to get_idle_action()

.github/workflows/format.yml, include/robot_interfaces/pybind_helper.hpp
Use run-clang-format from mpi_cmake_modules instead of running the obsolete custom action.
Through this PR.
=> chore: Update C++ formatting check

include/robot_interfaces/loggable.hpp, include/robot_interfaces/robot_driver.hpp, include/robot_interfaces/sensors/sensor_driver.hpp, tests/test_robot_logger.cpp
- Add virtual destructor to base classes that did not yet have one.
- Add casts to avoid comparison of signed and unsigned in tests.
`colcon build` and `colcon test`.
=> Fix clang-tidy warnings

CHANGELOG.md, include/robot_interfaces/status.hpp
If an error message passed to Status::set_error exceeds the maximum length Status::error_message can hold (currently 64 chars including terminating \0), it simply gets cut.  This can be a bit confusing.  To hopefully make it a bit more understandable, replace the last character in the string with `~` in this case (unfortunately more appropriate characters like … are not available with standard ASCII).
Using a test setup with the test bench.
=> Indicate shortened error messages

include/robot_interfaces/pybind_helper.hpp, include/robot_interfaces/robot_logger.hpp
Remove the now unused `loop` method and `block_size` argument. They were remnants from the now removed continuous writing mode.
Unit tests.
=> Remove obsolete code from RobotLogger

CHANGELOG.md, doc/custom_sensor.rst, doc_mainpage.rst, include/robot_interfaces/sensors/pybind_sensors.hpp, include/robot_interfaces/sensors/sensor_backend.hpp, include/robot_interfaces/sensors/sensor_data.hpp, include/robot_interfaces/sensors/sensor_driver.hpp, include/robot_interfaces/sensors/sensor_frontend.hpp, include/robot_interfaces/sensors/sensor_logger.hpp, include/robot_interfaces/utils.hpp, tests/test_sensor_logger.cpp
Add a `sensor_info` field to `SensorData` which can be used to provide static information about the sensor to the user.  A method `get_sensor_info()` is added to `SensorDriver` to fill the field in the backend.  It can then be accessed via a method of the same name in `SensorFrontend`.
By default, it provides an empty struct for backward compatibility.
Use this for data that doesn't change between observations (e.g. calibration parameters of frame rate).  Changing values should be added to the observation instead.
By implementing it in trifinger_cameras.
=> Add optional sensor_info to sensor interface

.github/workflows/build_master.yml, .github/workflows/build_pr.yml, .github/workflows/format.yml, .github/workflows/pr_todo_checks.yml
- Use ubuntu-latest instead of ubuntu-20.04 (20.04 will be disabled soon).
- Bump actions/checkout and setup-python to latest versions.
=> chore: Bump versions in GitHub workflows
