open-dynamic-robot-initiative/robot_interfaces

include/robot_interfaces/finger.hpp

Wrap the `RobotDriver` with a `MonitoredRobotDriver` inside the `RobotBackend`. The `MonitoredRobotDriver` holds the logic for monitoring the timing and makes sure that `shutdown()` is called on destruction.
This fixes the issue of the `RobotDriver` calling a pure virtual method (`shutdown()`) in its destructor.
With the original design, the `shutdown()` method is pure virtual at the
moment it is called in `~RobotDriver` (at this stage the implementation
of the derived class is not visible as the derived class is already
destroyed).
Resolve this by wrapping `RobotDriver` in a class `MonitoredRobotDriver`
which handles the timing monitoring (i.e. if actions are applied fast
enough).  In the actual `RobotDriver` class only the basic pure virtual
functions remain.  The call of the …

Wrap `RobotDriver` to fix pure virtual method call in destructor.

---

include/robot_interfaces/finger_logger.hpp
include/robot_interfaces/robot_backend.hpp
include/robot_interfaces/robot_data.hpp

Fix several compiler warnings (e.g. about initialization order, signed vs unsigned, etc).
Running some demo scripts on the Finger robot.

Fix several compiler warnings

---

CMakeLists.txt
src/robot_interfaces/__init__.py
srcpy/py_two_joint_types.cpp

added python bindings for running two joints with 1 motor-board

Two joint driver

---

CMakeLists.txt
include/robot_interfaces/trifinger_types.hpp
src/robot_interfaces/__init__.py
srcpy/py_trifinger_types.cpp

Add type definitions and Python bindings for the TriFinger robot.

Add TriFinger types.

---

demos/demo.cpp

The demo was merged with deprecated code in regards of the new namespace of robot_interfaces::status.

updated included and typedefs of demo

---

include/robot_interfaces/robot_backend.hpp

Trigger an error if the backend wants to apply the next action but none is available (and max. number of repetitions is exceeded).
Also add some documentation regarding the action repetition.
Running demo_fake_finger.py.  When setting the number of repetitions to zero, the print of position happening after 300 iterations takes too long and causes the error as expected. When allowing repetitions (1 is already enough), the error does not occur.

Trigger error if next action is not provided in time

---

demos/demo.cpp
include/robot_interfaces/monitored_robot_driver.hpp
include/robot_interfaces/robot.hpp
include/robot_interfaces/robot_frontend.hpp

The class Robot is a subclass of Frontend, which encapsulates a Backend.
This allows to construct a Frontend and a Backend in a single instance. This instance provides the same API as Frontend.
edit : In a supplementary commit, Robot takes the class RobotDriver as template, and construct the related instance. So, the frontend, the backend, the data and the driver instances are all instantiated via a single call.
demo.cpp was extended to also use Robot

added Robot, which encaspulate frontend and backend

---

CMakeLists.txt

Don't restrict to a specific OpenCV version.
Running demo_camera.py

Don't restrict to a specific OpenCV version.

---

include/robot_interfaces/robot_backend.hpp

Otherwise this results in a segmentation fault.
Only release GIL if Python is initialized, otherwise this results in a segmentation fault.
By running it both from Python and C++, verifying that it neither dead locks, nor segfaults.

Only release GIL if Python is initialized

---

include/robot_interfaces/robot_backend.hpp

Add max_number_of_actions to RobotBackend. If set to a value > 0, the backend automatically shuts down when the specified number of actions has been applied.
Using the fake finger demo.  I'm working on a proper unit test but this requires some fix in the backend which is beyond the scope of this feature, so will be done separately.

Add max_number_of_actions to RobotBackend

---

demos/demo_tricamera.py
include/robot_interfaces/sensors/pybind_sensors.hpp
include/robot_interfaces/sensors/pylon_driver.hpp

This is an intermediate step of setting the camera configuration from our software.
This only sets a few things for now (exposure time, frame rate and white balance).  The next step is to have a proper configuration file with all settings but this will be done in a later PR.
By running it on the platform.

Explicitly set some camera settings

---

include/robot_interfaces/sensors/pybind_sensors.hpp
include/robot_interfaces/sensors/sensor_data.hpp

Implement separate `SingleProcess-` and `MultiProcessSensorData` following the same pattern as for `RobotData`.
Using the camera demos in trifinger_cameras

Implement multi-process sensor data

---

CMakeLists.txt
package.xml

Add missing dependency on signal_handler
catbuild

fix: Add missing dependency on signal_handler

---

include/robot_interfaces/robot.hpp

RobotBackEnd allows for non realtime mode, but the Robot constructor did not have any related constructor. A new constructor has been added to Robot, which allows for the instantiation of a non realtime backend.
[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
A demo of a non realtime robot (in another package) compiled and worked. Testing this feature inside the robot_interfaces would require the programming of a new concrete non realtime driver. This did not seem required to me as the modifications just create instances of RobotBackEnd …

added non realtime constructor to robot

---

include/robot_interfaces/robot_backend.hpp

Based on https://github.com/pybind/pybind11/issues/2177#issuecomment-654784274, add a check with `PyGILState_Check()`.
By running unit tests.

Also check if GIL is actually held before releasing it

---

CMakeLists.txt
docs/index.md
docs/installation.md
docs/quick_start_example.md
docs/timeseries.md
include/robot_interfaces/status.hpp

Add some documentation for the doxygen build.
Building locally.

Add some documentation

---

include/robot_interfaces/robot_backend.hpp

Report termination reason of back end.  This is needed for better error handling.
With the submission system setup on roboch2.

Report termination reason of backend

---

CMakeLists.txt
package.xml
tests/CMakeLists.txt
tests/test_sensor_logger.cpp

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
ROS2 packaging: using ament and colcon and a little bit of warning hunt.

Warning hunt in unit-tests + ROS2 packaging

---

include/robot_interfaces/robot.hpp
include/robot_interfaces/robot_frontend.hpp
include/robot_interfaces/robot_log_reader.hpp
include/robot_interfaces/sensors/sensor_logger.hpp
include/robot_interfaces/types.hpp
srcpy/py_generic.cpp

Auto-reformat all code (using clang-format and black)

Auto-reformat code

---

tests/CMakeLists.txt

Use modern CMake for linking Boost
Ran unit tests.

Use modern CMake for linking Boost

---

CMakeLists.txt
python/robot_interfaces/__init__.py
srcpy/py_solo_eight_types.cpp

Implemented Interface for Solo8
By running it on Solo8

implemented solo8 interface

---

docs/installation.md

Update build instructions to use colcon

Update build instructions to use colcon

---

include/robot_interfaces/pybind_helper.hpp
srcpy/py_generic.cpp

- Add Python bindings for the time series
- Change the inconsistent licence header in the modified files.
Used in the new launcher setup to monitor when the first action is added to the robot data.

Add Python bindings for the time series

---

doc/real_time.rst

Add documentation regarding the real-time kernel.
Build the documentation locally.

doc: Add page regarding RT kernel

---

include/robot_interfaces/example.hpp
include/robot_interfaces/pybind_helper.hpp
include/robot_interfaces/robot_logger.hpp
tests/test_robot_logger.cpp

Reformat all C++ code using mpi_cpp_format.
Built the workspace.

Reformat C++ code

---

.github/workflows/format.yml

Add C++ formatting check (based on `mpi_cpp_format`) on pull requests.
Through this PR.

chore: Add C++ formatting check on pull requests

---

include/robot_interfaces/robot_backend.hpp

Log the loop rate of the backend.  When shutting down, print statistics and, if environment variable `ROBOT_BACKEND_TIME_LOG_FILE` is set, dump the full log to the specified file.
By running it on one of the robots.

Log loop rate in RobotBackend

---

include/robot_interfaces/robot_backend.hpp

If a limited episode length is set, set the size of the timer buffer
accordingly to ensure that the whole run is logged.
By running it on a robot and checking the resulting log.

Set frequency timer buffer to episode length

---

doc/breathing_cat.toml
doc_mainpage.rst

Use the new features of breathing cat 1.2.0

doc: Use custom mainpage and toctree

---

.github/workflows/pr_todo_checks.yml
CHANGELOG.md
CMakeLists.txt

See title.
By building and running tests.

find pybind11 before ament_cmake to fix error on Ubuntu 22.04

---

doc/about_architecture.rst
doc/preempt_rt_kernel.rst
doc/real_time.rst

- Restructure a bit to be (hopefully) easier to follow.
- Mention the new script to change the default kernel semi-automatically.
- Add info about using Nvidia drivers with PREEMPT_RT kernel (I only learned about this recently and don't have much experience with it yet, but heard from other people using it successfuly).
- Unrelated to the above but I noticed and fixed a bad reference target in about_architecture.rst
build locally.

doc: Update RT kernel pages
